#!/bin/bash

#set -x

trap display_time INT

function display_time() {
  ENDTIME=$(date +%s)
  SESSIONTIME=$((ENDTIME-STARTTIME))
  tput cub 2 #To clear the "^C" characters printed on pressing Ctrl+C
  echo "Full breath cycles: $COUNT"
  echo "Meditation Time: $(($SESSIONTIME / 3600)) hours, $((($SESSIONTIME / 60) % 60)) minutes and $(($SESSIONTIME % 60)) seconds"
  update_db "$STARTTIME" "$SESSIONTIME" $COUNT "$PATTERNNAME" "$PATTERN"
  exit 0
}

DEFAULTDB="meditate.db"

usage="Usage: ./$(basename $0) [OPTIONS]

Options:
 -p <player>            vlc, mpv, ffplay
 -t <seconds>           set meditation timer (default: infinite) (NOT IMPLEMENTED YET)
 -d <file>              sqlite db file (default: "$DEFAULTDB" in the same directory)
 -s [file]              show session details in the database
 -h                     this help"

illegal_option_error_msg="Illegal usage. Try $(basename $0) -h for usage."
no_player_error_msg="No Player selected. "$illegal_option_error_msg""
bold_text() { tput bold; echo -n "$1"; tput sgr0; }
dbfile_not_found_error_msg() { echo "DB file $(bold_text $1) not found."; }
dbfile_not_found_optiond_error_msg() { echo "$(dbfile_not_found_error_msg $1). Default file $(bold_text $DEFAULTDB) will be used."; }
schema_diff_error_msg() { echo "The $1 file has a different schema. If it's the default db, then it will be renamed and a new file will be created."; }
db_update_success_msg="DB updated."

setup_db() {
  createdbstmt='CREATE TABLE IF NOT EXISTS "meditated" (
	  "Session"	INTEGER PRIMARY KEY AUTOINCREMENT,
	  "StartTime"	TEXT NOT NULL,
    "StartTimeSeconds" REAL NOT NULL,
	  "Duration"	REAL NOT NULL,
	  "BreathCycles"	INTEGER NOT NULL,
	  "PatternName"	TEXT,
	  "Pattern"	TEXT NOT NULL
    )';
  sqlite3 "$1" "$createdbstmt";
}

update_db() {
  STARTTIMESECONDS="$1"
  SESSIONTIME="$2"
  STARTTIME=$(date --date=@$STARTTIMESECONDS)
  COUNT="$3"
  PATTERNNAME="$4"
  PATTERN="$5"
  insertstmt='INSERT INTO "meditated" ("StartTime", "StartTimeSeconds", "Duration", "BreathCycles", "PatternName", "Pattern")
    VALUES ("'"$STARTTIME"'", '"$STARTTIMESECONDS"','"$SESSIONTIME"','"$COUNT"',"'"$PATTERNNAME"'","'"$PATTERN"'");'
  #echo "Updating DB: $insertstmt";
  response=$(sqlite3 "$DBFILE" "$insertstmt" 2>&1);
  if [[ -z $response ]];
  then
    echo "$db_update_success_msg";
  else
    echo "Error: $response";
  fi
}

check_db_schema() {
  echo "Checking DB Schema"
  testdb="/tmp/test.db"
  setup_db "$testdb"
  diff=$(sqldiff -schema "$1" "$testdb")
  rm "$testdb"
  if [[ -n "$diff" ]];
  then
    schema_diff_error_msg "$1"
    return -1
  fi
}

display_db() {
  querystmt="SELECT Session, StartTime, Duration, BreathCycles, PatternName, Pattern from meditated;"
  DBFILE="$1";
  sqlite3 -header -column "$DBFILE" "$querystmt";
}

DBFILE="$DEFAULTDB"

while getopts ":hp:t:d:s:" opt; do
  case "${opt}" in
    h)
      echo "$usage"
      exit 0
      ;;
    p)
      PLAYEROPTION=("$OPTARG")
      if [[ "${#PLAYEROPTION[@]}" -gt 1 ]];
      then
        PLAYER="$OPTARG"
      else
        case "$OPTARG" in
          # TODO: Check if selected players exist
          vlc)
            PLAYER="vlc --intf dummy --no-loop --play-and-exit --quiet --no-version"
            ;;
          mpv)
            PLAYER="mpv --no-terminal"
            ;;
          ffplay)
            PLAYER="ffplay -nodisp -autoexit"
            ;;
          *)
          echo "$illegal_option_error_msg"
          exit 0
        esac
      fi
      ;;
    t)
      # Not implemented yet
      TIMER="$OPTARG"
      ;;
    d)
      DBFILE="${OPTARG}"
      if [[ ! -f "$DBFILE" ]];
      then
        dbfile_not_found_optiond_error_msg "$DBFILE"
        if [[ ! -f "$DEFAULTDB" ]];
        then
          setup_db "$DEFAULTDB"
          file="$DEFAULTDB"
        else
          check_db_schema "$DEFAULTDB"
          mv "$DEFAULTDB" "$DEFAULTDB.badschema"
          setup_db "$DEFAULTDB"
        fi
      else
        check_db_schema "$DBFILE"
        exit -1;
      fi
      ;;
    s)
      if [[ -f "$OPTARG" ]];
      then
        DBFILE="$OPTARG"
        display_db "$DBFILE"
      else
        dbfile_not_found_error_msg "$OPTARG"
      fi
      exit 0;
      ;;
    :)
      if [[ "$OPTARG" == "s" ]];
      then
        DBFILE="$DEFAULTDB"
        display_db "$DBFILE"
      fi
      exit 0;
      ;;
    ?)
      echo "$illegal_option_error_msg"
      exit 0
      ;;
  esac
done

#if [[ -z "$TIMER" ]];
#then
#  if [ ! -t 0 ] && [ ! -t 1 ]; then
#    exit -1;
#  echo
#  fi
#fi

FPATH=.
INHALE="$FPATH"/Inhale.mp3
HOLD="$FPATH"/Hold.mp3
EXHALE="$FPATH"/Exhale.mp3

INHALETIME=6
INHALEHOLDTIME=4
EXHALETIME=7
EXHALEHOLDTIME=3
PATTERNNAME="custom"
PATTERN="$INHALETIME $INHALEHOLDTIME $EXHALETIME $EXHALEHOLDTIME"

if [[ -z "$PLAYER" ]];
then
  echo "$no_player_error_msg";
  exit -1;
fi;

if [[ -z "$DBFILE" || ! -f "$DBFILE" ]];
then
  setup_db "$DEFAULTDB";
  DBFILE="$DEFAULTDB";
fi

check_db_schema "$DBFILE" || mv "$DBFILE" "$DBFILE.badschema" && setup_db "$DBFILE"

function breathe() {
  BREATHE="$1";
  BREATHETIME="$2";
  $PLAYER $BREATHE >&- 2>&-;
  sleep "$BREATHETIME";
}

function hold() {
  HOLD="$1"
  HOLDTIME="$2"
  $PLAYER $HOLD >&- 2>&-;
  sleep "$HOLDTIME";
}

function meditate() {
  COUNT=0;
  STARTTIME=$(date +%s);
  while true;
  do
    breathe $INHALE $INHALETIME;
    hold $HOLD $INHALEHOLDTIME;
    breathe $EXHALE $EXHALETIME;
    hold $HOLD $EXHALEHOLDTIME;
    COUNT=$((COUNT+1))
  done;
}

meditate

#while sleep $EXHALEHOLDTIME;
#do
#  count=$((count+1));
#  $PLAYER $INHALE >&- 2>&-;
#  sleep $INHALETIME;
#  $PLAYER $HOLD >&- 2>&-;
#  sleep $INHALEHOLDTIME;
#  $PLAYER $EXHALE >&- 2>&-;
#  sleep $EXHALETIME;
#  $PLAYER $HOLD >&- 2>&-;
#done